### ISSUE TITLE
Add play button

### ISSUE THREAD

**Issue by Tarkan67** [Tarkan67/capstone-project#1]
## Value Preposition

**As a User**
**I want to start the Game**
**to be able to play the Game**

## Description
<img width="184" alt="Screenshot 2022-03-24 at 10 02 17" src="https://user-images.githubusercontent.com/32304843/159880412-b238d48b-d473-4cb1-92d7-4ae40629f779.png">

Landing page with a start button.

## Acceptance Criteria

- [x] a button is shown
- [x] the button has a onClick
- [x] the onClick function starts the Game

## Tasks

(for developers team)

- [x] initialise next.js project
- [x] install mapbox, linter
- [ ] <s>add testing </s>
