### ISSUE TITLE
add log in

### ISSUE THREAD

**Issue by Tarkan67** [Tarkan67/capstone-project#11]
## Value Preposition

**As a User**
**I want to log in**
**to be able to have a profile and earn points by playing**

## Description

Log in with Github.

## Acceptance Criteria

- [x] log in button
- [x] mongoDB where the user is saved
- [x] log in with github

## Tasks

(for developers team)

- [x] setup mongoDB atlas
- [x] install mongoose
- [x] install auth
