### ISSUE TITLE
add profile overlay

### ISSUE THREAD

**Issue by Tarkan67** [Tarkan67/capstone-project#13]
## Value Preposition

**As a User**
**I want to see my profile**
**to be able to see if i'm logged in**

## Description
Profile-Page overlay

## Acceptance Criteria

- [x] a button is shown
- [x] the button has a onClick
- [x] the onClick function opens the overlay
- [x] the User Profile is seen on the overlay 

## Tasks

(for developers team)

- [x] install MUI
