### ISSUE TITLE
add picture randomizer

### ISSUE THREAD

**Issue by Tarkan67** [Tarkan67/capstone-project#2]
## Value Preposition

**As a User**
**I want to see a random picture**
**So that I don't know what picture will be shown**

## Description
<img width="720" alt="Screenshot 2022-03-24 at 10 03 59" src="https://user-images.githubusercontent.com/32304843/159880729-4a8df65e-6ea3-4983-96fd-3a716ffb5016.png">

After starting the Game, a random Elden Ring picture will be shown.

## Acceptance Criteria

- [x] a random picture will appear 
- [ ] the pictures that are marked as answered will not be shown

## Tasks

- [x] install npm package for randomizing
