### ISSUE TITLE
add a mapbox

### ISSUE THREAD

**Issue by Tarkan67** [Tarkan67/capstone-project#3]
## Value Preposition

**As a User**
**I want to see the Elden Ring map**
**to be able to give a guess where the location is**

## Description

A map is shown, it extends when clicked, after extending the next click will set a marker
<img width="600" alt="Screenshot 2022-03-24 at 10 06 03" src="https://user-images.githubusercontent.com/32304843/159881125-f4394595-fe29-453b-badb-68d9e8b3fa5f.png">
<img width="600" alt="Screenshot 2022-03-24 at 10 06 18" src="https://user-images.githubusercontent.com/32304843/159881162-b65d3681-bb7b-42a2-88d1-2a5e4f31941e.png">

## Acceptance Criteria

- [x] a map is shown below the picture
- [x] the map has an extend icon on the top right
- [x] after clicking the extend icon the map will fill the screen
- [x] when clicking in the map a marked icon will appear 
- [x] you can zoom in and out on the map
- [x] you can move around with dragging 

## Tasks

(for developers team)

- [x] set up mapbox with the elden ring map
